# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HomeWork-25' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HomeWork-25
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'

end
